// Generated by CoffeeScript 1.3.3
(function() {
  var AuthResultPacket;

  chrome.app.Routes[63] = AuthResultPacket = (function() {

    AuthResultPacket.prototype.id = 63;

    function AuthResultPacket(data) {
      this.success = function() {
        return data[0] === 0;
      };
      this.reason = function() {
        return data[0];
      };
    }

    return AuthResultPacket;

  })();

  PacketId.AuthResult = 63;

}).call(this);
