// Generated by CoffeeScript 1.4.0
(function() {

  chrome.app.Packets.ReceivedPacket = (function() {

    function ReceivedPacket() {}

    ReceivedPacket.prototype.attributes = function(data, map) {
      var fn;
      for (fn in map) {
        this.setAttribute(fn);
      }
      return this.data.parse(this, map);
    };

    ReceivedPacket.prototype.setAttribute = function(fn) {
      return this[fn] = function(value) {
        if (arguments.length === 0) {
          return this[fn].value;
        }
        this[fn].value = value;
        return this[fn].value;
      };
    };

    return ReceivedPacket;

  })();

}).call(this);
