// Generated by CoffeeScript 1.4.0
(function() {

  chrome.app.Packets.ReceivedPacket = (function() {

    function ReceivedPacket() {}

    ReceivedPacket.prototype.attributes = function(data, map) {
      var fn, type;
      for (fn in map) {
        type = map[fn];
        this[fn] = function(value) {
          if (arguments.length === 0) {
            return this[fn].value;
          }
          this[fn].value = value;
          return this[fn].value;
        };
      }
      return this.data.parse(this, map);
    };

    return ReceivedPacket;

  })();

}).call(this);
