// Generated by CoffeeScript 1.4.0
(function() {
  var CharInfoPacket;

  chrome.app.Routes[102] = CharInfoPacket = (function() {

    CharInfoPacket.prototype.id = 102;

    function CharInfoPacket(data) {
      this.data = data;
      this.data.parse(this, {
        name: "string",
        pledge: "string"
      });
    }

    CharInfoPacket.prototype.name = function(name) {
      if (arguments.length === 0) {
        return this._name;
      }
      return this._name = name;
    };

    CharInfoPacket.prototype.pledge = function(pledge) {
      if (arguments.length === 0) {
        return this._pledge;
      }
      return this._pledge = pledge;
    };

    return CharInfoPacket;

  })();

  PacketId.CharInfo = 102;

}).call(this);
