// Generated by CoffeeScript 1.4.0
(function() {
  var CharAmountPacket;

  chrome.app.Routes[80] = CharAmountPacket = (function() {

    CharAmountPacket.prototype.id = 80;

    function CharAmountPacket(data) {
      this.amount = function() {
        return data[0];
      };
      this.maximum = function() {
        return data[1];
      };
    }

    return CharAmountPacket;

  })();

  PacketId.CharAmount = 80;

}).call(this);
