// Generated by CoffeeScript 1.4.0
(function() {
  var CharInfoPacket,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  chrome.app.Routes[102] = CharInfoPacket = (function() {

    CharInfoPacket.prototype.id = 102;

    function CharInfoPacket(data) {
      this.data = data;
      this.pledge = __bind(this.pledge, this);

      this.name = __bind(this.name, this);

      this.data = this.data.string(this.name);
      this.data = this.data.string(this.pledge);
    }

    CharInfoPacket.prototype.name = function() {
      if (arguments.length === 0) {
        return this._name;
      }
      return this._name = arguments[0];
    };

    CharInfoPacket.prototype.pledge = function() {
      if (arguments.length === 0) {
        return this._pledge;
      }
      return this._pledge = arguments[0];
    };

    return CharInfoPacket;

  })();

  PacketId.CharInfo = 102;

}).call(this);
