// Generated by CoffeeScript 1.4.0
(function() {
  var ChatPacket,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  ChatPacket = (function() {

    function ChatPacket(data, opcode) {
      this.data = data;
      this.message = __bind(this.message, this);

      this.character = __bind(this.character, this);

      this.pid = __bind(this.pid, this);

      this.tid = __bind(this.tid, this);

      switch (opcode) {
        case 3:
          this.type = "global";
          this.data.parse(this, {
            tid: "int",
            message: "string"
          });
          break;
        case 47:
          this.type = "whisper";
          this.data.parse(this, {
            character: "string",
            message: "string"
          });
          break;
        case 71:
          this.type = "normal";
          this.data.parse(this, {
            tid: "int",
            pid: "long",
            message: "string"
          });
      }
    }

    ChatPacket.prototype.tid = function() {
      if (arguments.length === 0) {
        return this._tid;
      }
      return this._tid = arguments[0];
    };

    ChatPacket.prototype.pid = function() {
      if (arguments.length === 0) {
        return this._pid;
      }
      return this._pid = arguments[0];
    };

    ChatPacket.prototype.character = function() {
      if (arguments.length === 0) {
        return this._character;
      }
      return this._character = arguments[0];
    };

    ChatPacket.prototype.message = function() {
      if (arguments.length === 0) {
        return this._message;
      }
      return this._message = arguments[0];
    };

    return ChatPacket;

  })();

  chrome.app.Routes[3] = chrome.app.Routes[47] = chrome.app.Routes[71] = ChatPacket;

}).call(this);
