// Generated by CoffeeScript 1.4.0
(function() {
  var ChatPacket,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  ChatPacket = (function(_super) {

    __extends(ChatPacket, _super);

    ChatPacket.prototype.types = {
      0: "normal",
      2: "shouting",
      3: "global",
      4: "clan",
      12: "trade",
      16: "whisper"
    };

    function ChatPacket(data, opcode) {
      this.data = data;
      switch (opcode) {
        case 3:
          this.attributes(this.data, {
            tid: "int8",
            message: "string"
          });
          break;
        case 47:
          this.type = function() {
            return "whisper";
          };
          this.attributes(this.data, {
            character: "string",
            message: "string"
          });
          break;
        case 71:
          this.attributes(this.data, {
            tid: "int8",
            pid: "int32",
            message: "string"
          });
      }
    }

    ChatPacket.prototype.type = function() {
      return this.types[this.tid()];
    };

    return ChatPacket;

  })(chrome.app.Packets.ReceivedPacket);

  chrome.app.Routes[3] = chrome.app.Routes[47] = chrome.app.Routes[71] = ChatPacket;

}).call(this);
