// Generated by CoffeeScript 1.3.3
(function() {
  var MovePacket,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  MovePacket = (function(_super) {

    __extends(MovePacket, _super);

    MovePacket.prototype.id = 126;

    function MovePacket(data) {
      this.data = data;
      this.attributes(this.data, {
        characterId: "int32",
        x: "int16",
        y: "int16",
        heading: "int8"
      });
    }

    return MovePacket;

  })(chrome.app.Packets.ReceivedPacket);

  chrome.app.Routes[126] = MovePacket;

  PacketId.Move = 126;

}).call(this);
