// Generated by CoffeeScript 1.4.0
(function() {

  this.NewsPacket = (function() {

    function NewsPacket(data) {
      this.message = this.convertByteToChar(data).join("");
    }

    NewsPacket.prototype.convertByteToChar = function(bytes) {
      var byte, chars, _i, _len, _results;
      chars = [];
      _results = [];
      for (_i = 0, _len = bytes.length; _i < _len; _i++) {
        byte = bytes[_i];
        _results.push(chars[_i] = String.fromCharCode(byte));
      }
      return _results;
    };

    return NewsPacket;

  })();

}).call(this);
