// Generated by CoffeeScript 1.3.3
(function() {
  var NewsPacket;

  chrome.app.Routes[66] = NewsPacket = (function() {

    NewsPacket.prototype.id = 66;

    function NewsPacket(data) {
      this.message = this.convertByteToChar(data).join("");
    }

    NewsPacket.prototype.convertByteToChar = function(bytes) {
      var byte, chars, _i, _len, _results;
      chars = [];
      _results = [];
      for (_i = 0, _len = bytes.length; _i < _len; _i++) {
        byte = bytes[_i];
        if (byte === 0x00) {
          break;
        }
        _results.push(chars[_i] = String.fromCharCode(byte));
      }
      return _results;
    };

    return NewsPacket;

  })();

  PacketId.News = 63;

}).call(this);
