// Generated by CoffeeScript 1.4.0
(function() {
  var NewsPacket,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  chrome.app.Routes[66] = NewsPacket = (function() {

    NewsPacket.prototype.id = 66;

    function NewsPacket(data) {
      this.data = data;
      this.message = __bind(this.message, this);

      this.data.parse(this, {
        message: "string"
      });
    }

    NewsPacket.prototype.message = function() {
      if (arguments.length === 0) {
        return this._message;
      }
      return this._message = arguments[0];
    };

    return NewsPacket;

  })();

  PacketId.News = 63;

}).call(this);
