// Generated by CoffeeScript 1.3.3
(function() {
  var PlayerPacket,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  PlayerPacket = (function(_super) {

    __extends(PlayerPacket, _super);

    PlayerPacket.prototype.id = 1;

    function PlayerPacket(data) {
      this.data = data;
      this.attributes(this.data, {
        x: "int16",
        y: "int16",
        characterId: "int32",
        spriteId: "int16",
        status: "int8",
        heading: "int8",
        light: "int8",
        speed: "int8",
        experience: "int32",
        lawful: "int16",
        name: "string",
        title: "string"
      });
    }

    return PlayerPacket;

  })(chrome.app.Packets.ReceivedPacket);

  chrome.app.Routes[1] = PlayerPacket;

  PacketId.Player = 1;

}).call(this);
