// Generated by CoffeeScript 1.4.0
(function() {
  var PlayerPacket;

  PlayerPacket = (function() {

    PlayerPacket.prototype.id = 1;

    function PlayerPacket(data) {
      this.data = data;
      this.data.parse(this, {
        x: "long",
        y: "long"
      });
    }

    PlayerPacket.prototype.x = function(pos) {
      this.x = function(pos) {
        if (arguments.length === 0) {
          return this.x.value;
        }
        this.x.value = pos;
        return this.x.value;
      };
      return this.x(pos);
    };

    PlayerPacket.prototype.y = function(pos) {
      this.y = function(pos) {
        if (arguments.length === 0) {
          return this.y.value;
        }
        this.y.value = pos;
        return this.y.value;
      };
      return this.y(pos);
    };

    PlayerPacket.prototype.name = function(name) {
      return console.log(name);
    };

    PlayerPacket.prototype.pledge = function(name) {
      return console.log(name);
    };

    return PlayerPacket;

  })();

  chrome.app.Routes[1] = PlayerPacket;

  PacketId.Player = 1;

}).call(this);
