// Generated by CoffeeScript 1.3.3
(function() {
  var RemovePacket,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  RemovePacket = (function(_super) {

    __extends(RemovePacket, _super);

    RemovePacket.prototype.id = 0;

    function RemovePacket(data) {
      this.data = data;
      this.attributes(this.data, {
        characterId: "int32"
      });
    }

    return RemovePacket;

  })(chrome.app.Packets.ReceivedPacket);

  PacketId.Remove = 0;

  chrome.app.Routes[0] = RemovePacket;

}).call(this);
