// Generated by CoffeeScript 1.4.0
(function() {
  var TeleportPacket,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  TeleportPacket = (function(_super) {

    __extends(TeleportPacket, _super);

    TeleportPacket.prototype.id = 11;

    function TeleportPacket(data) {
      this.data = data;
      this.attributes(this.data, {
        unknown: "int16",
        characterId: "int32"
      });
    }

    return TeleportPacket;

  })(chrome.app.Packets.ReceivedPacket);

  PacketId.Teleport = 11;

  chrome.app.Routes[11] = TeleportPacket;

}).call(this);
