// Generated by CoffeeScript 1.3.3
(function() {
  var TimePacket,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  TimePacket = (function(_super) {

    __extends(TimePacket, _super);

    TimePacket.prototype.id = 58;

    function TimePacket(data) {
      this.data = data;
    }

    return TimePacket;

  })(chrome.app.Packets.ReceivedPacket);

  PacketId.Time = 58;

  chrome.app.Routes[58] = TimePacket;

}).call(this);
