// Generated by CoffeeScript 1.4.0
(function() {
  var ChatPacket,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  chrome.app.Packets.Chat.Global = ChatPacket = (function(_super) {

    __extends(ChatPacket, _super);

    function ChatPacket() {
      this["package"] = __bind(this["package"], this);
      ChatPacket.__super__.constructor.call(this, 115, ["message", "type"]);
      this.type();
    }

    ChatPacket.prototype.message = function() {
      if (arguments.length === 0) {
        return;
      }
      return this.process(arguments[0], "message");
    };

    ChatPacket.prototype.type = function() {
      return this.packed("type", 3 && 0xFF);
    };

    ChatPacket.prototype.length = function() {
      return ChatPacket.__super__.length.apply(this, arguments) + this.message().length + 1;
    };

    ChatPacket.prototype["package"] = function(buffer) {
      buffer.join([this.type()], 1);
      return buffer.join(this.message(), 2);
    };

    return ChatPacket;

  })(Packet);

}).call(this);
