// Generated by CoffeeScript 1.3.3
(function() {
  var Engine,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  chrome.app.Engine = Engine = (function() {
    /*
      # Elements are all the elements to load asynchronously
    */

    function Engine(elements) {
      this.render = __bind(this.render, this);

      this.load = __bind(this.load, this);

      var element, _i, _len;
      this.components = {};
      this.progress = new chrome.app.Engine.progress(elements);
      for (_i = 0, _len = elements.length; _i < _len; _i++) {
        element = elements[_i];
        this.load(element);
      }
    }

    Engine.prototype.load = function(element) {
      var _this = this;
      return $.get(element.url, function(data) {
        var finished;
        _this.components[element.name] = new element.logic(data);
        finished = _this.progress.update(element);
        if (finished) {
          return _this.render();
        }
      });
    };

    Engine.prototype.render = function() {
      var $background;
      $background = this.components.background.html();
      $(document.body).html($background);
      return $background.append(this.components.chat.html());
    };

    return Engine;

  })();

}).call(this);
