// Generated by CoffeeScript 1.3.3
(function() {
  var Progress,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  chrome.app.Engine.progress = Progress = (function() {

    function Progress(elements) {
      this.elements = elements;
      this.update = __bind(this.update, this);

    }

    Progress.prototype.update = function(el) {
      var idx;
      idx = this.elements.indexOf(el);
      this.elements.splice(idx, 1);
      return this.elements.length === 0;
    };

    return Progress;

  })();

}).call(this);
