// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  this.Encryptor = (function(_super) {

    __extends(Encryptor, _super);

    function Encryptor() {
      return Encryptor.__super__.constructor.apply(this, arguments);
    }

    Encryptor.prototype.process = function(data) {
      var keys, mask;
      keys = this.keys(this.seed);
      mask = this.mask(data);
      data[0] ^= keys[0];
      for (var i = 1; i < data.length; i++) {
        data[i] ^= (data[i - 1] ^ keys[i & 7])
    };

      data[3] = data[3] ^ keys[2];
      data[2] = data[2] ^ data[3] ^ keys[3];
      data[1] = data[1] ^ data[2] ^ keys[4];
      data[0] = data[0] ^ data[1] ^ keys[5];
      this.update(mask);
      return data;
    };

    return Encryptor;

  })(Encryption);

}).call(this);
