// Generated by CoffeeScript 1.4.0
(function() {
  var Character;

  chrome.app.Models.Character = Character = (function() {

    function Character(packet) {
      this.name = packet.name();
      this.pledge = packet.pledge();
    }

    Character.prototype.texture = function() {
      return PIXI.Texture.fromImage("assets/textures/bunny.png");
    };

    Character.prototype.sprite = function() {
      return new PIXI.Sprite(this.texture());
    };

    return Character;

  })();

}).call(this);
