// Generated by CoffeeScript 1.4.0
(function() {
  var Character;

  chrome.app.Models.Character = Character = (function() {

    function Character(packet) {
      this.name = packet.name();
      this.pledge = packet.pledge();
    }

    return Character;

  })();

}).call(this);
