// Generated by CoffeeScript 1.3.3
(function() {
  var Character;

  chrome.app.Models.Character = Character = (function() {

    function Character(packet) {
      this.name = packet.name();
      if (packet.x != null) {
        this.x = packet.x();
      }
      if (packet.y != null) {
        this.y = packet.y();
      }
      this.sprite = new PIXI.Sprite(this.texture());
      this.sprite.anchor.x = this.sprite.anchor.y = 0.5;
      this.sprite.speedX = this.sprite.speedY = 2;
    }

    Character.prototype.texture = function() {
      return PIXI.Texture.fromImage("assets/textures/bunny.png");
    };

    return Character;

  })();

}).call(this);
