// Generated by CoffeeScript 1.4.0
(function() {
  var Player,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  chrome.app.Models.Player = Player = (function(_super) {

    __extends(Player, _super);

    function Player(packet) {
      this.pledge = packet.pledge();
      Player.__super__.constructor.apply(this, arguments);
    }

    return Player;

  })(chrome.app.Models.Character);

}).call(this);
