// Generated by CoffeeScript 1.4.0
(function() {
  var Lineage,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Lineage = (function() {

    function Lineage() {
      this.log = __bind(this.log, this);
      this.socket = new Socket("127.0.0.1", 2000);
      this.controllers = [];
    }

    Lineage.prototype.log = function(user, pwd) {
      var packet,
        _this = this;
      packet = new LogPacket(113);
      packet.user = user;
      packet.password = pwd;
      packet.bufferize(function(buffer) {
        return _this.socket.send(buffer);
      });
      return packet;
    };

    return Lineage;

  })();

  this.Lineage = new Lineage();

}).call(this);
