// Generated by CoffeeScript 1.3.3
(function() {
  var Lineage;

  Lineage = (function() {

    function Lineage() {
      var login;
      this.socket = new Socket("127.0.0.1", 2000);
      this.controllers = [];
      login = new chrome.app.Controllers.Login;
      this.push(login);
    }

    Lineage.prototype.push = function(controller) {
      controller.render();
      return this.controllers.push(controller);
    };

    Lineage.prototype.pop = function(controller) {
      return this.controllers.slice(this.controllers.indexOf(controller), 0);
    };

    Lineage.prototype.current = function() {
      return this.controllers[this.controllers.length - 1];
    };

    return Lineage;

  })();

  $(function() {
    return window.Lineage = new Lineage();
  });

}).call(this);
