// Generated by CoffeeScript 1.3.3
(function() {

  chrome.app.Routes = [];

  chrome.app.Controllers = {};

  chrome.app.Models = {};

  chrome.app.Packets = {};

  chrome.app.Components = {};

  this.PacketId = {};

}).call(this);
