// Generated by CoffeeScript 1.3.3
(function() {
  var CharactersController;

  chrome.app.Controllers.Characters = CharactersController = (function() {

    function CharactersController() {
      var packet;
      packet = new chrome.app.Packets.Click();
      packet.bufferize(Lineage.socket.send);
    }

    CharactersController.prototype.render = function() {
      var _this = this;
      if (this.$template == null) {
        $.get(this.templateURL(), function(text) {
          _this.$template = $(text);
          return _this.render();
        });
        return this;
      }
      $(document.body).html(this.$template);
      return this.eventify(this.$template);
    };

    CharactersController.prototype.templateURL = function() {
      return "/templates/characters.html";
    };

    CharactersController.prototype.eventify = function($html) {};

    CharactersController.prototype.received = function(packet) {
      return console.log(packet);
    };

    return CharactersController;

  })();

}).call(this);
