// Generated by CoffeeScript 1.4.0
(function() {
  var CharactersController;

  chrome.app.Controllers.Characters = CharactersController = (function() {

    function CharactersController() {
      var packet;
      packet = new chrome.app.Packets.Click();
      packet.onReady(Lineage.socket.send);
    }

    CharactersController.prototype.render = function() {
      var _this = this;
      if (this.$template == null) {
        $.get(this.templateURL(), function(text) {
          _this.$template = $(text);
          return _this.render();
        });
        return this;
      }
      $(document.body).html(this.$template);
      return this.eventify(this.$template);
    };

    CharactersController.prototype.templateURL = function() {
      return "/templates/characters.html";
    };

    CharactersController.prototype.eventify = function($html) {
      return $html.on("click", ".select", function() {
        var character;
        character = $(this).parent().data("character");
        return Lineage.push(new chrome.app.Controllers.Game(character));
      });
    };

    CharactersController.prototype.received = function(packet) {
      switch (packet.id) {
        case PacketId.CharAmount:
          this.characters = new Array();
          this.characters.amount = packet.amount();
          break;
        case PacketId.CharInfo:
          this.characters.push(new chrome.app.Models.Player(packet));
          if (this.characters.amount === this.characters.length) {
            this.update();
          }
      }
      return console.log(packet);
    };

    CharactersController.prototype.update = function() {
      var $li, $list, $ul, character, _i, _len, _ref;
      $list = $("#charactersList");
      $list.empty();
      $ul = $("<ul>");
      _ref = this.characters;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        character = _ref[_i];
        $li = $("<li>");
        $li.append("<h3>" + character.name + "</h3>");
        $li.append("<a href='#' class='select'>Select</a>");
        $li.data("character", character);
        $ul.append($li);
      }
      return $list.html($ul);
    };

    return CharactersController;

  })();

}).call(this);
