// Generated by CoffeeScript 1.4.0
(function() {
  var GameController;

  chrome.app.Controllers.Game = GameController = (function() {

    function GameController(character) {
      var packet;
      this.character = character;
      packet = new chrome.app.Packets.SelectCharacter(this.character);
      packet.bufferize(Lineage.socket.send);
    }

    GameController.prototype.render = function() {
      $(document.body).empty();
      return Crafty.init(document.width, document.height);
    };

    return GameController;

  })();

}).call(this);
