// Generated by CoffeeScript 1.4.0
(function() {
  var GameController,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  chrome.app.Controllers.Game = GameController = (function() {

    function GameController(player) {
      var $container, packet, sprite;
      this.player = player;
      this.render = __bind(this.render, this);

      packet = new chrome.app.Packets.SelectCharacter(this.player);
      packet.bufferize(Lineage.socket.send);
      this.stage = new PIXI.Stage(0xFFFFFF);
      this.renderer = PIXI.autoDetectRenderer(1024, 768);
      this.components();
      $container = $("<div id='game'>").appendTo($(document.body).empty());
      $container.append(this.renderer.view);
      sprite = this.player.sprite();
      sprite.position.x = this.renderer.width / 2;
      sprite.position.y = this.renderer.height / 2;
      sprite.anchor.x = 0.5;
      sprite.anchor.y = 0.5;
      this.stage.addChild(sprite);
      this.eventify($(document.body));
      this.renderer.render(this.stage);
      requestAnimationFrame(this.render);
    }

    GameController.prototype.components = function() {
      if (this.components.value != null) {
        if (arguments.length === 0) {
          return this.components.value;
        }
        return this.components.value[arguments[0]];
      }
      this.components.value = {};
      this.components.value.chat = new chrome.app.Components.Chat;
      return this.components.value;
    };

    GameController.prototype.render = function() {
      this.renderer.render(this.stage);
      return requestAnimationFrame(this.render);
    };

    GameController.prototype.eventify = function($html) {
      var _this = this;
      $html.on("submit", "form", function(e) {
        var $input, global, message, packet;
        $input = $(this).children("input").first();
        message = $input.val();
        $input.val("");
        global = $("#chat ul.types li.active").hasClass("global");
        packet = new chrome.app.Packets.Chat(message, global);
        packet.bufferize(Lineage.socket.send);
        return false;
      });
      return $html.on("click", "#chat ul.types li", function(e) {
        return _this.components("chat").toggle($(e.target));
      });
    };

    GameController.prototype.received = function(packet) {
      switch (packet.id) {
        case PacketId.Chat:
        case PacketId.GlobalChat:
        case PacketId.WhisperChat:
          this.components("chat").received(packet);
          break;
        case PacketId.CharInfo:
          this.update(this.player.find(packet));
          break;
        case PacketId.Player:
          console.log(packet);
      }
      return console.log(packet);
    };

    return GameController;

  })();

}).call(this);
