// Generated by CoffeeScript 1.3.3
(function() {
  var LoginController,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  chrome.app.Controllers.Login = LoginController = (function() {

    function LoginController() {
      this.receivedTemplate = __bind(this.receivedTemplate, this);

    }

    LoginController.prototype.login = function(user, password) {
      var packet;
      packet = new chrome.app.Packets.Login(user, password);
      return packet.bufferize(Lineage.socket.send);
    };

    LoginController.prototype.received = function(packet) {
      switch (packet.id) {
        case PacketId.AuthResult:
          if (packet.success() === true) {
            return Lineage.push(new chrome.app.Controllers.Characters);
          } else {

          }
      }
    };

    LoginController.prototype.render = function() {
      var _this = this;
      if (this.$template == null) {
        $.get(this.templateURL(), function(text) {
          _this.$template = $(text);
          return _this.render();
        });
        return this;
      }
      $(document.body).html(this.$template);
      return this.eventify(this.$template);
    };

    LoginController.prototype.templateURL = function() {
      return "/templates/login.html";
    };

    LoginController.prototype.eventify = function($html) {
      var _this = this;
      return $html.on("submit", function() {
        var password, username;
        username = $html.find("#login_username").val();
        password = $html.find("#login_password").val();
        _this.login(username, password);
        return false;
      });
    };

    LoginController.prototype.receivedTemplate = function(text) {
      return this.template = $(text);
    };

    return LoginController;

  })();

}).call(this);
