// Generated by CoffeeScript 1.4.0
(function() {

  this.LoginController = (function() {

    function LoginController(html) {}

    LoginController.prototype.received = function(packet) {};

    return LoginController;

  })();

}).call(this);
