// Generated by CoffeeScript 1.4.0
(function() {

  Int8Array.prototype.join = function(arr, offset) {
    var int, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = arr.length; _i < _len; _i++) {
      int = arr[_i];
      this[offset] = int;
      _results.push(offset++);
    }
    return _results;
  };

}).call(this);
