// Generated by CoffeeScript 1.4.0
(function() {

  Int8Array.prototype.join = function(arr, offset) {
    var idx, int, _i, _len;
    if (offset == null) {
      offset = 0;
    }
    for (idx = _i = 0, _len = arr.length; _i < _len; idx = ++_i) {
      int = arr[idx];
      this[offset + idx] = int;
    }
    return arr.length;
  };

}).call(this);
