// Generated by CoffeeScript 1.4.0
(function() {

  String.prototype.bufferize = function(callback) {
    var b, f;
    b = new Blob([this]);
    f = new FileReader();
    f.onload = function(e) {
      return callback(new Uint8Array(e.target.result));
    };
    f.readAsArrayBuffer(b);
    return this;
  };

}).call(this);
