// Generated by CoffeeScript 1.4.0
(function() {

  Uint8Array.prototype.join = function(arr, offset) {
    var int, _i, _len;
    for (_i = 0, _len = arr.length; _i < _len; _i++) {
      int = arr[_i];
      this[offset] = int;
      offset++;
    }
    return arr.length;
  };

  Uint8Array.prototype.string = function(callback) {
    var byte, chars, _i, _len;
    chars = [];
    for (_i = 0, _len = this.length; _i < _len; _i++) {
      byte = this[_i];
      if (byte === 0x00) {
        break;
      }
      chars[_i] = String.fromCharCode(byte);
    }
    callback(chars.join(""));
    return this.subarray(++chars.length);
  };

  Uint8Array.prototype.int = function(callback) {
    callback(this[0]);
    return this.subarray(1);
  };

  Uint8Array.prototype.long = function(callback) {
    var byte, long, _i, _len, _ref;
    long = 0;
    _ref = this.subarray(0, 4);
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      byte = _ref[_i];
      long |= byte << (8 * _i);
    }
    callback(long);
    return this.subarray(4);
  };

}).call(this);
