// Generated by CoffeeScript 1.3.3
(function() {

  Uint8Array.prototype.join = function(arr, offset) {
    var int, _i, _len;
    for (_i = 0, _len = arr.length; _i < _len; _i++) {
      int = arr[_i];
      this[offset] = int;
      offset++;
    }
    return arr.length;
  };

}).call(this);
