// Generated by CoffeeScript 1.4.0
(function() {

  this.Templates = (function() {

    function Templates() {}

    Templates.prototype.get = function(file, obj) {
      var request;
      request = new XMLHttpRequest();
      request.callbackObject = obj;
      request.file = file;
      request.addEventListener("load", this.requestLoaded);
      request.addEventListener("error", this.requestFailed);
      request.open("get", file);
      return request.send();
    };

    Templates.prototype.requestLoaded = function() {
      this.callbackObject["html"].call(this.callbackObject, this.responseText);
      return this.callbackObject["loaded"].call(this.callbackObject);
    };

    Templates.prototype.requestFailed = function() {
      throw "Template Error: " + this;
    };

    return Templates;

  })();

}).call(this);
