// Generated by CoffeeScript 1.3.3
(function() {
  var Camera;

  chrome.app.Components.Camera = Camera = (function() {

    function Camera(renderer) {
      this.renderer = renderer;
      this.center = {
        x: this.renderer.width / 2,
        y: this.renderer.height / 2
      };
    }

    Camera.prototype.move = function(character, delta) {};

    Camera.prototype.position = function(character, delta) {
      character.sprite.position.x = this.center.x + delta.x * 32;
      return character.sprite.position.y = this.center.y + delta.y * 32;
    };

    Camera.prototype.update = function(stage) {
      return this.renderer.render(stage);
    };

    return Camera;

  })();

}).call(this);
