// Generated by CoffeeScript 1.3.3
(function() {
  var Characters;

  chrome.app.Components.Characters = Characters = (function() {

    function Characters(stage, player) {
      this.stage = stage;
      this.player = player;
      this.onScreen = [];
      this.add(this.player);
    }

    Characters.prototype.add = function(character) {
      this.stage.addChild(character.sprite);
      this.onScreen.push(character);
      return character.sprite.mouseover = function(data) {
        return console.log(data.target.character.name);
      };
    };

    Characters.prototype.remove = function(character) {
      this.stage.removeChild(character.sprite);
      return this.onScreen.splice(this.onScreen.indexOf(character), 1);
    };

    Characters.prototype.isOnScreen = function(character) {
      return this.onScreen.indexOf(character) !== -1;
    };

    Characters.prototype.delta = function(character) {
      return {
        x: character.x - this.player.x,
        y: character.y - this.player.y
      };
    };

    return Characters;

  })();

}).call(this);
