// Generated by CoffeeScript 1.3.3
(function() {
  var Chat;

  chrome.app.Components.Chat = Chat = (function() {

    function Chat() {
      Lineage.templates.get("templates/chat.html", this);
      this.history = {
        normal: [],
        whisper: [],
        global: [],
        clan: [],
        trade: []
      };
    }

    Chat.prototype.html = function(html) {
      if (arguments.length === 0) {
        return this.html.value;
      }
      this.html.value = $(html);
      return this.html.value;
    };

    Chat.prototype.loaded = function() {
      $("#game").append(this.html());
      this.$types = this.html().find("ul.types");
      this.$types.children(".global").addClass("active");
      return this.$active = this.$types.children(".active");
    };

    Chat.prototype.received = function(packet) {
      return this.update(packet.type(), this.compile(packet));
    };

    Chat.prototype.compile = function(packet) {
      if (packet.type() === "whisper") {
        return $("<li>" + (packet.character()) + ": " + (packet.message()) + "</li>");
      } else {
        return $("<li>" + (packet.message()) + "</li>");
      }
    };

    Chat.prototype.update = function(type, $li) {
      var $el;
      $el = this.html().find("." + type);
      this.history[type].push($li);
      if (this.$active.hasClass(type)) {
        return this.html().find(".history").append($li);
      }
    };

    Chat.prototype.toggle = function($element) {
      this.html().find(".active").removeClass("active");
      $element.addClass("active");
      this.$active = $element;
      return this.html().find(".history").html(this.history[$element.attr("type")]);
    };

    Chat.prototype.send = function(message, type) {
      var packet;
      packet = new chrome.app.Packets.Chat(message, type);
      return packet.bufferize(Lineage.socket.send);
    };

    return Chat;

  })();

}).call(this);
