// Generated by CoffeeScript 1.4.0
(function() {
  var ChatPacket,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  chrome.app.Packets.Chat = ChatPacket = (function(_super) {

    __extends(ChatPacket, _super);

    function ChatPacket(message, global) {
      this.message = message;
      if (global == null) {
        global = false;
      }
      this["package"] = __bind(this["package"], this);

      this.type = global ? 3 : 0;
      ChatPacket.__super__.constructor.call(this, global ? 115 : 18);
    }

    ChatPacket.prototype.length = function() {
      return ChatPacket.__super__.length.apply(this, arguments) + this.message.length + 2;
    };

    ChatPacket.prototype["package"] = function(view) {
      var _this = this;
      view.join([this.type & 0xFF], 1);
      return this.message.bufferize(function(msg) {
        view.join(msg, 2);
        return _this.packaged(view);
      });
    };

    return ChatPacket;

  })(Packet);

}).call(this);
