// Generated by CoffeeScript 1.4.0
(function() {
  var ClickPacket,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  chrome.app.Packets.Click = ClickPacket = (function(_super) {

    __extends(ClickPacket, _super);

    function ClickPacket() {
      ClickPacket.__super__.constructor.call(this, 46);
    }

    return ClickPacket;

  })(Packet);

}).call(this);
