// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  this.LogPacket = (function(_super) {

    __extends(LogPacket, _super);

    function LogPacket() {
      return LogPacket.__super__.constructor.apply(this, arguments);
    }

    LogPacket.prototype.length = function() {
      return LogPacket.__super__.length.apply(this, arguments) + this.user.length + this.password.length + 2;
    };

    LogPacket.prototype["package"] = function(view) {
      var idx,
        _this = this;
      idx = 1;
      return this.user.bufferize(function(user) {
        view.join(user, idx);
        idx += user.length;
        view.join(0x00, ++idx);
        idx++;
        return _this.password.bufferize(function(pwd) {
          view.join(pwd, idx);
          idx += pwd.length;
          view.join(0x00, ++idx);
          idx++;
          return _this.packaged(view);
        });
      });
    };

    return LogPacket;

  })(Packet);

}).call(this);
