// Generated by CoffeeScript 1.4.0
(function() {
  var LogPacket,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  chrome.app.Packets.Login = LogPacket = (function(_super) {

    __extends(LogPacket, _super);

    function LogPacket(user, password) {
      LogPacket.__super__.constructor.call(this, 113, ["user", "password"]);
      this.user(user);
      this.password(password);
    }

    LogPacket.prototype.user = function() {
      if (arguments.length === 0) {
        return;
      }
      return this.process(arguments[0], "user");
    };

    LogPacket.prototype.password = function() {
      if (arguments.length === 0) {
        return;
      }
      return this.process(arguments[0], "password");
    };

    LogPacket.prototype.length = function() {
      return LogPacket.__super__.length.apply(this, arguments) + this.user().length + this.password().length;
    };

    LogPacket.prototype["package"] = function(buffer) {
      buffer.join(this.user(), 1);
      return buffer.join(this.password(), this.user().length + 1);
    };

    return LogPacket;

  })(Packet);

}).call(this);
