// Generated by CoffeeScript 1.4.0
(function() {
  var SelectCharacterPacket,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  chrome.app.Packets.SelectCharacter = SelectCharacterPacket = (function(_super) {

    __extends(SelectCharacterPacket, _super);

    function SelectCharacterPacket(character) {
      this["package"] = __bind(this["package"], this);
      this.character = character;
      SelectCharacterPacket.__super__.constructor.call(this, 89);
    }

    SelectCharacterPacket.prototype.length = function() {
      return SelectCharacterPacket.__super__.length.apply(this, arguments) + this.character.name.length + 1;
    };

    SelectCharacterPacket.prototype["package"] = function(view) {
      var _this = this;
      return this.character.name.bufferize(function(name) {
        view.join(name, 1);
        return _this.packaged(view);
      });
    };

    return SelectCharacterPacket;

  })(Packet);

}).call(this);
