// Generated by CoffeeScript 1.4.0
(function() {
  var SelectCharacterPacket,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  chrome.app.Packets.SelectCharacter = SelectCharacterPacket = (function(_super) {

    __extends(SelectCharacterPacket, _super);

    function SelectCharacterPacket(character) {
      this.character = character;
      SelectCharacterPacket.__super__.constructor.call(this, 89, ["name"]);
      this.name(this.character.name);
    }

    SelectCharacterPacket.prototype.name = function() {
      if (arguments.length === 0) {
        return;
      }
      return this.process(arguments[0], "name");
    };

    SelectCharacterPacket.prototype.length = function() {
      return SelectCharacterPacket.__super__.length.apply(this, arguments) + this.name().length;
    };

    SelectCharacterPacket.prototype.packaged = function(buffer) {
      return buffer.join(this.name(), 1);
    };

    return SelectCharacterPacket;

  })(Packet);

}).call(this);
